all: compile
	# ./quick
	./heap
compile: quick_sort.cpp
	# g++ -o quick quick_sort.cpp -Wall -Werror -Wunused -pedantic -std=c++1z
	g++ -o heap heap_sort.cpp -Wall -Werror -Wunused -pedantic -std=c++11
clean:
	rm quick heap
